version: "3.1"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:5000
    depends_on:
      - mysql
  mysql:
    image: mysql:8.3.0
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_app
volumes:
  db_data:
