version: "3.1"
name: todo-lan
services:
  app:
    container_name: silvia_app
    image: todo-app_image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:5000
    volumes:
      - ./app:/app
    depends_on:
      - mysql
    networks:
      - todo-lan
  mysql:
    container_name: silvia_mysql
    image: mysql:8.3.0
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_app
    networks:
      - todo-lan

volumes:
  db_data:

networks:
  todo-lan:
    driver: bridge
